package Vista;

import Modelo.*;
import java.awt.Color;
import java.io.IOException;
import java.io.Serializable;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

// Interfaz grafica que le aparece a cada jugador, el diseno es un placeholder porque ocupamos poner el tablero y el historial (yo hago el historial)

public class InterfazCliente extends javax.swing.JFrame implements Serializable{

    public Cliente refCliente;
    private String nombreTurno = "";            // Nombre del jugador cuyo turno es actualmente
    private String nombreJugador = "";          // Nombre del jugador
    /**
     * Creates new form ChatCliente
     */
    public InterfazCliente() {
        initComponents();
        this.getLblAtaque2Luchador1().setVisible(false);
        this.getLblAtaque2Luchador2().setVisible(false);
        this.getLblAtaque2Luchador3().setVisible(false);
      //  lblDado1.setOpaque(true);
      //  lblDado2.setOpaque(true);
    }

    public void setRefCliente(Cliente refCliente) {
        this.refCliente = refCliente;
    }
    
    public Cliente getRefCliente() {
        return refCliente;
    }
    
    public void setNombreTurno(String nombreTurno) {
        this.nombreTurno = nombreTurno;
        lblTurno.setText("Es turno de: " + nombreTurno);
    }

    public void setNombreJugador(String nombreJugador){
        this.nombreJugador = nombreJugador;
        lblNombreJugador.setText(nombreJugador);
    }

    public String getNombreJugador() {
        return nombreJugador;
    }

    public JPanel getPnlTablero() {
        return pnlTablero;
    }

    public void setPnlTablero(JPanel pnlTablero) {
        this.pnlTablero = pnlTablero;
    }

    public JPanel getPnlTablero2() {
        return pnlTablero2;
    }

    public void setPnlTablero2(JPanel pnlTablero2) {
        this.pnlTablero2 = pnlTablero2;
    }
    
    
    public void addMensaje(String msj)              // Para agregar un mensaje en la interfaz del cliente
    {
        //txaMensajes.append(msj + "\n");
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTurno = new javax.swing.JLabel();
        lblUsuarioLanzamiento = new javax.swing.JLabel();
        lblConsola = new javax.swing.JLabel();
        lblNombreJugador = new javax.swing.JLabel();
        lblStatusPartida = new javax.swing.JLabel();
        lblLog = new javax.swing.JLabel();
        spResultado = new javax.swing.JScrollPane();
        txaResultado = new javax.swing.JTextArea();
        spLog = new javax.swing.JScrollPane();
        txaLog = new javax.swing.JTextArea();
        pnlTablero = new javax.swing.JPanel();
        pnlInfo = new javax.swing.JPanel();
        lblImagenLuchador2 = new javax.swing.JLabel();
        lblImagenLuchador3 = new javax.swing.JLabel();
        lblImagenLuchador1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblHumanidadLuchador1 = new javax.swing.JLabel();
        lblNombreLuchador1 = new javax.swing.JLabel();
        lblAtaque1Luchador1 = new javax.swing.JLabel();
        lblAtaque2Luchador1 = new javax.swing.JLabel();
        lblPoderLuchador1 = new javax.swing.JLabel();
        lblResistenciaLuchador1 = new javax.swing.JLabel();
        lblAutosanidadLuchador1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblHumanidadLuchador3 = new javax.swing.JLabel();
        lblNombreLuchador3 = new javax.swing.JLabel();
        lblAtaque1Luchador3 = new javax.swing.JLabel();
        lblAtaque2Luchador3 = new javax.swing.JLabel();
        lblPoderLuchador3 = new javax.swing.JLabel();
        lblResistenciaLuchador3 = new javax.swing.JLabel();
        lblAutosanidadLuchador3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblHumanidadLuchador2 = new javax.swing.JLabel();
        lblNombreLuchador2 = new javax.swing.JLabel();
        lblAtaque1Luchador2 = new javax.swing.JLabel();
        lblAtaque2Luchador2 = new javax.swing.JLabel();
        lblPoderLuchador2 = new javax.swing.JLabel();
        lblResistenciaLuchador2 = new javax.swing.JLabel();
        lblAutosanidadLuchador2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        pnlTablero2 = new javax.swing.JPanel();
        lblCasillasDestruidas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombre2Luchador1 = new javax.swing.JLabel();
        lblNumCasillasLuchador1 = new javax.swing.JLabel();
        lblVidaLuchador1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNombre2Luchador2 = new javax.swing.JLabel();
        lblNumCasillasLuchador2 = new javax.swing.JLabel();
        lblVidaLuchador2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNombre2Luchador3 = new javax.swing.JLabel();
        lblNumCasillasLuchador3 = new javax.swing.JLabel();
        lblVidaLuchador3 = new javax.swing.JLabel();
        lblVidaTotal = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaChat = new javax.swing.JTextArea();
        lblChat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txfConsola = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaConsola = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTurno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(255, 255, 255));
        lblTurno.setText("Es turno de: ");
        jPanel1.add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 230, 29));
        jPanel1.add(lblUsuarioLanzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1156, 516, 3, 68));

        lblConsola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConsola.setForeground(new java.awt.Color(255, 255, 255));
        lblConsola.setText("Consola");
        jPanel1.add(lblConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, -1, -1));

        lblNombreJugador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombreJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreJugador.setText("Sin nombre...");
        jPanel1.add(lblNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 210, 29));

        lblStatusPartida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatusPartida.setForeground(new java.awt.Color(255, 255, 255));
        lblStatusPartida.setText("Estado de partida: Esperando jugadores");
        jPanel1.add(lblStatusPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 280, 30));

        lblLog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLog.setForeground(new java.awt.Color(255, 255, 255));
        lblLog.setText("Bitácora");
        jPanel1.add(lblLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        txaResultado.setEditable(false);
        txaResultado.setBackground(new java.awt.Color(51, 51, 51));
        txaResultado.setColumns(20);
        txaResultado.setForeground(new java.awt.Color(255, 255, 255));
        txaResultado.setRows(5);
        txaResultado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txaResultado.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        spResultado.setViewportView(txaResultado);

        jPanel1.add(spResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 400, 300));

        txaLog.setEditable(false);
        txaLog.setBackground(new java.awt.Color(51, 51, 51));
        txaLog.setColumns(20);
        txaLog.setForeground(new java.awt.Color(255, 255, 255));
        txaLog.setRows(5);
        txaLog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txaLog.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        spLog.setViewportView(txaLog);

        jPanel1.add(spLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 400, 310));

        pnlTablero.setBackground(new java.awt.Color(51, 51, 51));
        pnlTablero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(pnlTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 640, 510));

        pnlInfo.setBackground(new java.awt.Color(51, 51, 51));
        pnlInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        lblImagenLuchador2.setBackground(new java.awt.Color(0, 0, 0));
        lblImagenLuchador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        lblImagenLuchador2.setOpaque(true);

        lblImagenLuchador3.setBackground(new java.awt.Color(0, 0, 0));
        lblImagenLuchador3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        lblImagenLuchador3.setOpaque(true);

        lblImagenLuchador1.setBackground(new java.awt.Color(0, 0, 0));
        lblImagenLuchador1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        lblImagenLuchador1.setOpaque(true);

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        lblHumanidadLuchador1.setForeground(new java.awt.Color(255, 255, 255));
        lblHumanidadLuchador1.setText("Porcentaje Humanidad");

        lblNombreLuchador1.setForeground(new java.awt.Color(204, 0, 204));
        lblNombreLuchador1.setText("Nombre");

        lblAtaque1Luchador1.setForeground(new java.awt.Color(204, 102, 0));
        lblAtaque1Luchador1.setText("Grupo #1");

        lblAtaque2Luchador1.setForeground(new java.awt.Color(204, 102, 0));
        lblAtaque2Luchador1.setText("Grupo #2");

        lblPoderLuchador1.setForeground(new java.awt.Color(255, 255, 255));
        lblPoderLuchador1.setText("Poder:");

        lblResistenciaLuchador1.setForeground(new java.awt.Color(255, 255, 255));
        lblResistenciaLuchador1.setText("Resistencia:");

        lblAutosanidadLuchador1.setForeground(new java.awt.Color(255, 255, 255));
        lblAutosanidadLuchador1.setText("Autosanidad:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResistenciaLuchador1)
                    .addComponent(lblPoderLuchador1)
                    .addComponent(lblAutosanidadLuchador1)
                    .addComponent(lblHumanidadLuchador1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreLuchador1)
                            .addComponent(lblAtaque1Luchador1)
                            .addComponent(lblAtaque2Luchador1))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblHumanidadLuchador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreLuchador1)
                .addGap(12, 12, 12)
                .addComponent(lblAtaque1Luchador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAtaque2Luchador1)
                .addGap(12, 12, 12)
                .addComponent(lblPoderLuchador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResistenciaLuchador1)
                .addGap(12, 12, 12)
                .addComponent(lblAutosanidadLuchador1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        lblHumanidadLuchador3.setForeground(new java.awt.Color(255, 255, 255));
        lblHumanidadLuchador3.setText("Porcentaje Humanidad");

        lblNombreLuchador3.setForeground(new java.awt.Color(204, 0, 204));
        lblNombreLuchador3.setText("Nombre");

        lblAtaque1Luchador3.setForeground(new java.awt.Color(204, 102, 0));
        lblAtaque1Luchador3.setText("Grupo #1");

        lblAtaque2Luchador3.setForeground(new java.awt.Color(204, 102, 0));
        lblAtaque2Luchador3.setText("Grupo #2");

        lblPoderLuchador3.setForeground(new java.awt.Color(255, 255, 255));
        lblPoderLuchador3.setText("Poder:");

        lblResistenciaLuchador3.setForeground(new java.awt.Color(255, 255, 255));
        lblResistenciaLuchador3.setText("Resistencia:");

        lblAutosanidadLuchador3.setForeground(new java.awt.Color(255, 255, 255));
        lblAutosanidadLuchador3.setText("Autosanidad:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResistenciaLuchador3)
                    .addComponent(lblPoderLuchador3)
                    .addComponent(lblAutosanidadLuchador3)
                    .addComponent(lblHumanidadLuchador3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreLuchador3)
                            .addComponent(lblAtaque1Luchador3)
                            .addComponent(lblAtaque2Luchador3))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblHumanidadLuchador3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreLuchador3)
                .addGap(12, 12, 12)
                .addComponent(lblAtaque1Luchador3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAtaque2Luchador3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPoderLuchador3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResistenciaLuchador3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAutosanidadLuchador3)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        lblHumanidadLuchador2.setForeground(new java.awt.Color(255, 255, 255));
        lblHumanidadLuchador2.setText("Porcentaje Humanidad");

        lblNombreLuchador2.setForeground(new java.awt.Color(204, 0, 204));
        lblNombreLuchador2.setText("Nombre");

        lblAtaque1Luchador2.setForeground(new java.awt.Color(204, 102, 0));
        lblAtaque1Luchador2.setText("Grupo #1");

        lblAtaque2Luchador2.setForeground(new java.awt.Color(204, 102, 0));
        lblAtaque2Luchador2.setText("Grupo #2");

        lblPoderLuchador2.setForeground(new java.awt.Color(255, 255, 255));
        lblPoderLuchador2.setText("Poder:");

        lblResistenciaLuchador2.setForeground(new java.awt.Color(255, 255, 255));
        lblResistenciaLuchador2.setText("Resistencia:");

        lblAutosanidadLuchador2.setForeground(new java.awt.Color(255, 255, 255));
        lblAutosanidadLuchador2.setText("Autosanidad:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResistenciaLuchador2)
                    .addComponent(lblPoderLuchador2)
                    .addComponent(lblAutosanidadLuchador2)
                    .addComponent(lblHumanidadLuchador2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreLuchador2)
                            .addComponent(lblAtaque1Luchador2)
                            .addComponent(lblAtaque2Luchador2))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblHumanidadLuchador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreLuchador2)
                .addGap(12, 12, 12)
                .addComponent(lblAtaque1Luchador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAtaque2Luchador2)
                .addGap(12, 12, 12)
                .addComponent(lblPoderLuchador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResistenciaLuchador2)
                .addGap(12, 12, 12)
                .addComponent(lblAutosanidadLuchador2))
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stats");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImagenLuchador3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagenLuchador1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lblImagenLuchador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagenLuchador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagenLuchador2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagenLuchador3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 360, 610));

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 255, 255));
        lblResultado.setText("Resultado del ataque (Recibido/Ejecutado)");
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        pnlTablero2.setBackground(new java.awt.Color(51, 51, 51));
        pnlTablero2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        lblCasillasDestruidas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCasillasDestruidas.setForeground(new java.awt.Color(255, 255, 255));
        lblCasillasDestruidas.setText("Casillas destruidas");

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        lblNombre2Luchador1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre2Luchador1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre2Luchador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre2Luchador1.setText("Luchador 1");

        lblNumCasillasLuchador1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNumCasillasLuchador1.setForeground(new java.awt.Color(255, 255, 255));
        lblNumCasillasLuchador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumCasillasLuchador1.setText("Número de casillas");

        lblVidaLuchador1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblVidaLuchador1.setForeground(new java.awt.Color(255, 255, 255));
        lblVidaLuchador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVidaLuchador1.setText("Vida");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumCasillasLuchador1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVidaLuchador1)
                            .addComponent(lblNombre2Luchador1))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblNombre2Luchador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVidaLuchador1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumCasillasLuchador1)
                .addGap(24, 24, 24))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        lblNombre2Luchador2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre2Luchador2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre2Luchador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre2Luchador2.setText("Luchador 2");

        lblNumCasillasLuchador2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNumCasillasLuchador2.setForeground(new java.awt.Color(255, 255, 255));
        lblNumCasillasLuchador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumCasillasLuchador2.setText("Número de casillas");

        lblVidaLuchador2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblVidaLuchador2.setForeground(new java.awt.Color(255, 255, 255));
        lblVidaLuchador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVidaLuchador2.setText("Vida");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumCasillasLuchador2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVidaLuchador2)
                            .addComponent(lblNombre2Luchador2))
                        .addGap(12, 12, 12)))
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblNombre2Luchador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVidaLuchador2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumCasillasLuchador2)
                .addGap(30, 30, 30))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        lblNombre2Luchador3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre2Luchador3.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre2Luchador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre2Luchador3.setText("Luchador 3");

        lblNumCasillasLuchador3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNumCasillasLuchador3.setForeground(new java.awt.Color(255, 255, 255));
        lblNumCasillasLuchador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumCasillasLuchador3.setText("Número de casillas");

        lblVidaLuchador3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblVidaLuchador3.setForeground(new java.awt.Color(255, 255, 255));
        lblVidaLuchador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVidaLuchador3.setText("Vida");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumCasillasLuchador3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVidaLuchador3)
                            .addComponent(lblNombre2Luchador3))
                        .addGap(14, 14, 14)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblNombre2Luchador3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVidaLuchador3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumCasillasLuchador3)
                .addGap(36, 36, 36))
        );

        lblVidaTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVidaTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblVidaTotal.setText("Vida");

        javax.swing.GroupLayout pnlTablero2Layout = new javax.swing.GroupLayout(pnlTablero2);
        pnlTablero2.setLayout(pnlTablero2Layout);
        pnlTablero2Layout.setHorizontalGroup(
            pnlTablero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablero2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVidaTotal)
                .addGap(137, 137, 137)
                .addComponent(lblCasillasDestruidas)
                .addGap(113, 113, 113))
            .addGroup(pnlTablero2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        pnlTablero2Layout.setVerticalGroup(
            pnlTablero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablero2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTablero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVidaTotal)
                    .addComponent(lblCasillasDestruidas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTablero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(pnlTablero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 640, 120));

        txaChat.setEditable(false);
        txaChat.setBackground(new java.awt.Color(51, 51, 51));
        txaChat.setColumns(20);
        txaChat.setForeground(new java.awt.Color(255, 255, 255));
        txaChat.setRows(5);
        txaChat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txaChat.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(txaChat);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 680, 540, 210));

        lblChat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblChat.setForeground(new java.awt.Color(255, 255, 255));
        lblChat.setText("Chat");
        jPanel1.add(lblChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 660, -1, -1));

        txfConsola.setBackground(new java.awt.Color(51, 51, 51));
        txfConsola.setForeground(new java.awt.Color(255, 255, 255));
        txfConsola.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txfConsola.setCaretColor(new java.awt.Color(255, 255, 255));
        txfConsola.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txfConsola);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 840, 870, 50));

        txaConsola.setEditable(false);
        txaConsola.setBackground(new java.awt.Color(51, 51, 51));
        txaConsola.setColumns(20);
        txaConsola.setForeground(new java.awt.Color(255, 255, 255));
        txaConsola.setRows(5);
        txaConsola.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txaConsola.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txaConsola);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 870, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblStatusPartida() {
        return lblStatusPartida;
    }

    public void setLblStatusPartida(JLabel lblStatusPartida) {
        this.lblStatusPartida = lblStatusPartida;
    }

    
    public void setInicioPartida(){             // Configura la partida con los datos iniciales para empezarla
        lblStatusPartida.setText("Estado de partida: Iniciada");
   //     lblDinero.setText("Dinero: $" + refCliente.getHiloCliente().getDinero());
   //     lblNumCasas.setText("Numero de casas: " + refCliente.getHiloCliente().getNumCasas());
   //     lblNumHoteles.setText("Numero de hoteles: " + refCliente.getHiloCliente().getNumHoteles());
   //     lblNumPropiedades.setText("Numero de propiedades: " + refCliente.getHiloCliente().getNumPropiedades());
    }
    
    public void seleccionFicha(){
        
        //infoBox("Por favor escoja la ficha que desesa.","Selección de ficha");
    }
    
    public void pintarLanzamientoDados (int valor1, int valor2, String usuario){    // Para escribir en la interfaz del cliente los valores de los dice rolls    
        
     //   lblDado1.setText(valor1 + "");
     //   lblDado2.setText(valor2 + "");
     //   lblDado1.setBackground(Color.red);
     //   lblDado2.setBackground(Color.red);
        
    //    if (!btnLanzarDados.isEnabled())
    //        btnLanzarDados.setEnabled(true);
        
        lblUsuarioLanzamiento.setText(usuario);
    }
    
    
    public void pintarTurno(String turno){              // Para escribir en la interfaz del cliente el jugador que está jugando actualmente
        this.nombreTurno = turno;
        lblTurno.setText("Es turno de " + turno);
    }

    public JTextField getTxfConsola() {
        return txfConsola;
    }

    public void setTxfConsola(JTextField txfConsola) {
        this.txfConsola = txfConsola;
    }

    public JTextArea getTxaConsola() {
        return txaConsola;
    }

    public void setTxaConsola(JTextArea txaConsola) {
        this.txaConsola = txaConsola;
    }

    public JTextArea getTxaChat() {
        return txaChat;
    }

    public void setTxaChat(JTextArea txaChat) {
        this.txaChat = txaChat;
    }

    public JTextArea getTxaLog() {
        return txaLog;
    }

    public void setTxaLog(JTextArea txaLog) {
        this.txaLog = txaLog;
    }

    public JTextArea getTxaResultado() {
        return txaResultado;
    }

    public void setTxaResultado(JTextArea txaResultado) {
        this.txaResultado = txaResultado;
    }

    public JLabel getLblAtaque1Luchador1() {
        return lblAtaque1Luchador1;
    }

    public void setLblAtaque1Luchador1(JLabel lblAtaque1Luchador1) {
        this.lblAtaque1Luchador1 = lblAtaque1Luchador1;
    }

    public JLabel getLblAtaque1Luchador2() {
        return lblAtaque1Luchador2;
    }

    public void setLblAtaque1Luchador2(JLabel lblAtaque1Luchador2) {
        this.lblAtaque1Luchador2 = lblAtaque1Luchador2;
    }

    public JLabel getLblAtaque1Luchador3() {
        return lblAtaque1Luchador3;
    }

    public void setLblAtaque1Luchador3(JLabel lblAtaque1Luchador3) {
        this.lblAtaque1Luchador3 = lblAtaque1Luchador3;
    }

    public JLabel getLblAtaque2Luchador1() {
        return lblAtaque2Luchador1;
    }

    public void setLblAtaque2Luchador1(JLabel lblAtaque2Luchador1) {
        this.lblAtaque2Luchador1 = lblAtaque2Luchador1;
    }

    public JLabel getLblAtaque2Luchador2() {
        return lblAtaque2Luchador2;
    }

    public void setLblAtaque2Luchador2(JLabel lblAtaque2Luchador2) {
        this.lblAtaque2Luchador2 = lblAtaque2Luchador2;
    }

    public JLabel getLblAtaque2Luchador3() {
        return lblAtaque2Luchador3;
    }

    public void setLblAtaque2Luchador3(JLabel lblAtaque2Luchador3) {
        this.lblAtaque2Luchador3 = lblAtaque2Luchador3;
    }

    public JLabel getLblAutosanidadLuchador1() {
        return lblAutosanidadLuchador1;
    }

    public void setLblAutosanidadLuchador1(JLabel lblAutosanidadLuchador1) {
        this.lblAutosanidadLuchador1 = lblAutosanidadLuchador1;
    }

    public JLabel getLblAutosanidadLuchador2() {
        return lblAutosanidadLuchador2;
    }

    public void setLblAutosanidadLuchador2(JLabel lblAutosanidadLuchador2) {
        this.lblAutosanidadLuchador2 = lblAutosanidadLuchador2;
    }

    public JLabel getLblAutosanidadLuchador3() {
        return lblAutosanidadLuchador3;
    }

    public void setLblAutosanidadLuchador3(JLabel lblAutosanidadLuchador3) {
        this.lblAutosanidadLuchador3 = lblAutosanidadLuchador3;
    }

    public JLabel getLblCasillasDestruidas() {
        return lblCasillasDestruidas;
    }

    public void setLblCasillasDestruidas(JLabel lblCasillasDestruidas) {
        this.lblCasillasDestruidas = lblCasillasDestruidas;
    }

    public JLabel getLblHumanidadLuchador1() {
        return lblHumanidadLuchador1;
    }

    public void setLblHumanidadLuchador1(JLabel lblHumanidadLuchador1) {
        this.lblHumanidadLuchador1 = lblHumanidadLuchador1;
    }

    public JLabel getLblHumanidadLuchador2() {
        return lblHumanidadLuchador2;
    }

    public void setLblHumanidadLuchador2(JLabel lblHumanidadLuchador2) {
        this.lblHumanidadLuchador2 = lblHumanidadLuchador2;
    }

    public JLabel getLblHumanidadLuchador3() {
        return lblHumanidadLuchador3;
    }

    public void setLblHumanidadLuchador3(JLabel lblHumanidadLuchador3) {
        this.lblHumanidadLuchador3 = lblHumanidadLuchador3;
    }

    public JLabel getLblImagenLuchador1() {
        return lblImagenLuchador1;
    }

    public void setLblImagenLuchador1(JLabel lblImagenLuchador1) {
        this.lblImagenLuchador1 = lblImagenLuchador1;
    }

    public JLabel getLblImagenLuchador2() {
        return lblImagenLuchador2;
    }

    public void setLblImagenLuchador2(JLabel lblImagenLuchador2) {
        this.lblImagenLuchador2 = lblImagenLuchador2;
    }

    public JLabel getLblImagenLuchador3() {
        return lblImagenLuchador3;
    }

    public void setLblImagenLuchador3(JLabel lblImagenLuchador3) {
        this.lblImagenLuchador3 = lblImagenLuchador3;
    }

    public JLabel getLblNombre2Luchador1() {
        return lblNombre2Luchador1;
    }

    public void setLblNombre2Luchador1(JLabel lblNombre2Luchador1) {
        this.lblNombre2Luchador1 = lblNombre2Luchador1;
    }

    public JLabel getLblNombre2Luchador2() {
        return lblNombre2Luchador2;
    }

    public void setLblNombre2Luchador2(JLabel lblNombre2Luchador2) {
        this.lblNombre2Luchador2 = lblNombre2Luchador2;
    }
    
    

    public JLabel getLblNombre2Luchador3() {
        return lblNombre2Luchador3;
    }

    public void setLblNombre2Luchador3(JLabel lblNombre2Luchador3) {
        this.lblNombre2Luchador3 = lblNombre2Luchador3;
    }

    public JLabel getLblNombreJugador() {
        return lblNombreJugador;
    }

    public void setLblNombreJugador(JLabel lblNombreJugador) {
        this.lblNombreJugador = lblNombreJugador;
    }

    public JLabel getLblNombreLuchador1() {
        return lblNombreLuchador1;
    }

    public void setLblNombreLuchador1(JLabel lblNombreLuchador1) {
        this.lblNombreLuchador1 = lblNombreLuchador1;
    }

    public JLabel getLblNombreLuchador2() {
        return lblNombreLuchador2;
    }

    public void setLblNombreLuchador2(JLabel lblNombreLuchador2) {
        this.lblNombreLuchador2 = lblNombreLuchador2;
    }

    public JLabel getLblNombreLuchador3() {
        return lblNombreLuchador3;
    }

    public void setLblNombreLuchador3(JLabel lblNombreLuchador3) {
        this.lblNombreLuchador3 = lblNombreLuchador3;
    }

    public JLabel getLblNumCasillasLuchador1() {
        return lblNumCasillasLuchador1;
    }

    public void setLblNumCasillasLuchador1(JLabel lblNumCasillasLuchador1) {
        this.lblNumCasillasLuchador1 = lblNumCasillasLuchador1;
    }

    public JLabel getLblNumCasillasLuchador2() {
        return lblNumCasillasLuchador2;
    }

    public void setLblNumCasillasLuchador2(JLabel lblNumCasillasLuchador12) {
        this.lblNumCasillasLuchador2 = lblNumCasillasLuchador12;
    }

    public JLabel getLblNumCasillasLuchador3() {
        return lblNumCasillasLuchador3;
    }

    public void setLblNumCasillasLuchador3(JLabel lblNumCasillasLuchador3) {
        this.lblNumCasillasLuchador3 = lblNumCasillasLuchador3;
    }

    public JLabel getLblPoderLuchador1() {
        return lblPoderLuchador1;
    }

    public void setLblPoderLuchador1(JLabel lblPoderLuchador1) {
        this.lblPoderLuchador1 = lblPoderLuchador1;
    }

    public JLabel getLblPoderLuchador2() {
        return lblPoderLuchador2;
    }

    public void setLblPoderLuchador2(JLabel lblPoderLuchador2) {
        this.lblPoderLuchador2 = lblPoderLuchador2;
    }

    public JLabel getLblPoderLuchador3() {
        return lblPoderLuchador3;
    }

    public void setLblPoderLuchador3(JLabel lblPoderLuchador3) {
        this.lblPoderLuchador3 = lblPoderLuchador3;
    }

    public JLabel getLblResistenciaLuchador1() {
        return lblResistenciaLuchador1;
    }

    public void setLblResistenciaLuchador1(JLabel lblResistenciaLuchador1) {
        this.lblResistenciaLuchador1 = lblResistenciaLuchador1;
    }

    public JLabel getLblResistenciaLuchador2() {
        return lblResistenciaLuchador2;
    }

    public void setLblResistenciaLuchador2(JLabel lblResistenciaLuchador2) {
        this.lblResistenciaLuchador2 = lblResistenciaLuchador2;
    }

    public JLabel getLblResistenciaLuchador3() {
        return lblResistenciaLuchador3;
    }

    public void setLblResistenciaLuchador3(JLabel lblResistenciaLuchador3) {
        this.lblResistenciaLuchador3 = lblResistenciaLuchador3;
    }

    public JLabel getLblResultado() {
        return lblResultado;
    }

    public void setLblResultado(JLabel lblResultado) {
        this.lblResultado = lblResultado;
    }

    public JLabel getLblTurno() {
        return lblTurno;
    }

    public void setLblTurno(JLabel lblTurno) {
        this.lblTurno = lblTurno;
    }

    public JLabel getLblUsuarioLanzamiento() {
        return lblUsuarioLanzamiento;
    }

    public void setLblUsuarioLanzamiento(JLabel lblUsuarioLanzamiento) {
        this.lblUsuarioLanzamiento = lblUsuarioLanzamiento;
    }

    public JLabel getLblVidaLuchador1() {
        return lblVidaLuchador1;
    }

    public void setLblVidaLuchador1(JLabel lblVidaLuchador1) {
        this.lblVidaLuchador1 = lblVidaLuchador1;
    }

    public JLabel getLblVidaLuchador2() {
        return lblVidaLuchador2;
    }

    public void setLblVidaLuchador2(JLabel lblVidaLuchador2) {
        this.lblVidaLuchador2 = lblVidaLuchador2;
    }

    public JLabel getLblVidaLuchador3() {
        return lblVidaLuchador3;
    }

    public void setLblVidaLuchador3(JLabel lblVidaLuchador3) {
        this.lblVidaLuchador3 = lblVidaLuchador3;
    }

    public JLabel getLblVidaTotal() {
        return lblVidaTotal;
    }

    public void setLblVidaTotal(JLabel lblVidaTotal) {
        this.lblVidaTotal = lblVidaTotal;
    }

    

    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAtaque1Luchador1;
    private javax.swing.JLabel lblAtaque1Luchador2;
    private javax.swing.JLabel lblAtaque1Luchador3;
    private javax.swing.JLabel lblAtaque2Luchador1;
    private javax.swing.JLabel lblAtaque2Luchador2;
    private javax.swing.JLabel lblAtaque2Luchador3;
    private javax.swing.JLabel lblAutosanidadLuchador1;
    private javax.swing.JLabel lblAutosanidadLuchador2;
    private javax.swing.JLabel lblAutosanidadLuchador3;
    private javax.swing.JLabel lblCasillasDestruidas;
    private javax.swing.JLabel lblChat;
    private javax.swing.JLabel lblConsola;
    private javax.swing.JLabel lblHumanidadLuchador1;
    private javax.swing.JLabel lblHumanidadLuchador2;
    private javax.swing.JLabel lblHumanidadLuchador3;
    private javax.swing.JLabel lblImagenLuchador1;
    private javax.swing.JLabel lblImagenLuchador2;
    private javax.swing.JLabel lblImagenLuchador3;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblNombre2Luchador1;
    private javax.swing.JLabel lblNombre2Luchador2;
    private javax.swing.JLabel lblNombre2Luchador3;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JLabel lblNombreLuchador1;
    private javax.swing.JLabel lblNombreLuchador2;
    private javax.swing.JLabel lblNombreLuchador3;
    private javax.swing.JLabel lblNumCasillasLuchador1;
    private javax.swing.JLabel lblNumCasillasLuchador2;
    private javax.swing.JLabel lblNumCasillasLuchador3;
    private javax.swing.JLabel lblPoderLuchador1;
    private javax.swing.JLabel lblPoderLuchador2;
    private javax.swing.JLabel lblPoderLuchador3;
    private javax.swing.JLabel lblResistenciaLuchador1;
    private javax.swing.JLabel lblResistenciaLuchador2;
    private javax.swing.JLabel lblResistenciaLuchador3;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblStatusPartida;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblUsuarioLanzamiento;
    private javax.swing.JLabel lblVidaLuchador1;
    private javax.swing.JLabel lblVidaLuchador2;
    private javax.swing.JLabel lblVidaLuchador3;
    private javax.swing.JLabel lblVidaTotal;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlTablero;
    private javax.swing.JPanel pnlTablero2;
    private javax.swing.JScrollPane spLog;
    private javax.swing.JScrollPane spResultado;
    private javax.swing.JTextArea txaChat;
    private javax.swing.JTextArea txaConsola;
    private javax.swing.JTextArea txaLog;
    private javax.swing.JTextArea txaResultado;
    private javax.swing.JTextField txfConsola;
    // End of variables declaration//GEN-END:variables
}
